spring.application.name=docflow
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/docflow
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB
app.upload.path=C:/docflow/uploads

spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=a@kkkvd.ru
spring.mail.password=??????_??????????
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

logging.level.root=INFO
logging.level.kkkvd.docflow=DEBUG
logging.level.org.hibernate.SQL=DEBUG

app.admin.password=${ADMIN_PASSWORD:236Sync75df}

spring.jpa.open-in-view=false